# Documentation deployment workflow.

# Documentation is always deployed for master and releases branch.
# deployed  is deployed on the latest release branch or on the new
# latest release. This prevents bugfixes on older releases to override the
# latest documentation.
name: documentation
on:
  push:
    branches:
      - "release-*"
      - master
  release:
    types:
      - published

env:
  PYTHON_VERSION: 3.x

jobs:
  check:
    name: Check if docs should be deployed
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.verify.outputs.deploy }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract release version from the branch name (or tag)
        id: branch_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const branchName = process.env.GITHUB_REF_NAME
            const prefix = 'v'
            const releaseVersion = branchName.substring(branchName.lastIndexOf('-') + 1, branchName.length)
            return releaseVersion.startsWith(prefix) ? releaseVersion : prefix + releaseVersion

      - name: Get latest repository version
        id: latest_release_version
        uses: oprypin/find-latest-tag@v1.1.0
        with:
          repository: ${{ github.repository }}
          prefix: 'v'

      - name: Verify if the latest version contains current branch/tag version
        id: verify
        env:
          LATEST_VERSION: ${{ steps.latest_release_version.outputs.tag }}
          BRANCH_VERSION: ${{ steps.branch_version.outputs.result }}
        run: |
          echo "::set-output name=latestVersion::${{ env.LATEST_VERSION }}"
          echo "::set-output name=branchVersion::${{ env.LATEST_VERSION }}"
          echo "::set-output name=deploy::${{ contains(env.LATEST_VERSION, env.BRANCH_VERSION) }}"

      - name: Set up Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install \
            jinja2>=3.1 \
            markdown>=3.3 \
            mkdocs>=1.3 \
            mkdocs-material>=8.2.11 \
            mkdocs-material-extensions>=1.0.3 \
            mkdocs-minify-plugin>=0.5 \
            mkdocs-redirects>=1.0 \
            pygments>=2.11 \
            pymdown-extensions>=9.3

      - name: Deploy documentation
        env:
          BRANCH_VERSION: ${{ steps.branch_version.outputs.result }}
        run: |
          mike deploy --push --update-aliases ${{ BRANCH_VERSION }}
          
      - name: Update documentation alias for latest
        env:
          LATEST_VERSION: ${{ steps.latest_release_version.outputs.tag }}
          BRANCH_VERSION: ${{ steps.branch_version.outputs.result }}
        if: ${{ contains(env.LATEST_VERSION, env.BRANCH_VERSION) }}
        run: |
          mike deploy --push --update-aliases latest
          mike set-default --push latest

  # documentation:
  #   name: Build and deploy docs
  #   runs-on: ubuntu-latest
  #   needs: check
  #   if: needs.check.outputs.deploy == 'true'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Python runtime
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: ${{ env.PYTHON_VERSION }}

  #     - name: Install Python dependencies
  #       run: |
  #         pip install \
  #           jinja2>=3.1 \
  #           markdown>=3.3 \
  #           mkdocs>=1.3 \
  #           mkdocs-material>=8.2.11 \
  #           mkdocs-material-extensions>=1.0.3 \
  #           mkdocs-minify-plugin>=0.5 \
  #           mkdocs-redirects>=1.0 \
  #           pygments>=2.11 \
  #           pymdown-extensions>=9.3

  #     - name: Deploy documentation
  #           # Assume 
  #           # } else {
  #           # if $ver == latest {
  #           #   mike deploy --push --update-aliases $ver latest
  #           # } else {
  #           #   mike deploy --push --update-aliases $ver
  #           # }
  #           # mkdocs gh-deploy --force
  #       run: |
  #         mike set-default --push latest
  #         mike deploy --push --update-aliases 0.1 latest
          
