name: documentation
on:
  push:
    branches:
      - "release-*"
      #- master
      #- feature/multiple-servers

env:
  PYTHON_VERSION: 3.x

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install \
            jinja2>=3.1 \
            markdown>=3.3 \
            mkdocs>=1.3 \
            mkdocs-material>=8.2.11 \
            mkdocs-material-extensions>=1.0.3 \
            mkdocs-minify-plugin>=0.5 \
            mkdocs-redirects>=1.0 \
            pygments>=2.11 \
            pymdown-extensions>=9.3
      # mike >= 1.2 \

      - name: Extract release version from branch name
        id: branch_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const branchName = process.env.GITHUB_REF
            const releaseVersion = branchName.substring( branchName.lastIndexOf('-') + 1 , branchName.length )
            return "v" + releaseVersion

      - name: Get latest release version
        id: latest_release_version
        uses: "WyriHaximus/github-action-get-previous-tag@v1.1.0"

      # - name: Deploy documentation if on latest branch
      #   run: mike deploy --push --update-aliases ${{ steps.branch_version.outputs.result }}

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
        if: contains( steps.latest_release_version.outputs.result, steps.branch_version.outputs.result )


